### ISSUE TITLE
Ask about the use of the repository

### ISSUE THREAD

**Issue by huxiaoyi520** [lycantrope/deeplabcut-analysis#2]
Hello, I am a deeplabcut use of novice, for the use of the repository, there are some questions to understand, hope the author can give answers, thanks! Does the repository use deeplabcut to train and tag animals and A, B, and C in the Y Maze, and then import the tagged video into the library to analyze the detailed data required?

**Comment by lycantrope** [comment]
> Hello, I am a deeplabcut use of novice, for the use of the repository, there are some questions to understand, hope the author can give answers, thanks! Does the repository use deeplabcut to train and tag animals and A, B, and C in the Y Maze, and then import the tagged video into the library to analyze the detailed data required?

Thank you for your question.
You are right, this repository is used for analyzing and plotting the coordinates of animals with in the Y-maze arena. To adapt this repository, you have to follow the DeepLabCut protocol to obtain the coordinates of animals.

**Comment by huxiaoyi520** [comment]
Thank you for your reply. Does the repository not provide sample data?Can you provide sample data to learn about the repository? Thank you very much for your help.  My e-mail address is 492545176@qq. com

**Comment by lycantrope** [comment]
Unfortunately, I could not directly provide you the data for personal use. 
Please check our published [paper](https://doi.org/10.3233/jad-240033), and contact the corresponding author via e-mail to request the usage of the data. I will close this issue.

**Comment by huxiaoyi520** [comment]
Hello, I have contacted the corresponding author by Email, as follows:

Dear Professor Hayashi,
We are highly interested in the behavioral data analysis section of your published article. Would it be possible for you to share the raw data used in analyzing the behavioral data through DeepLabCut as presented in your paper? This would greatly assist us in learning from the DeepLabCut scripts employed in your research.
We are eagerly awaiting your reply.
Thank you,
