### ISSUE TITLE
data format 

### ISSUE THREAD

**Issue by huxiaoyi520** [lycantrope/deeplabcut-analysis#4]
Sorry to bother you again.

I just want to know the format of the data, if you can't provide the raw data, then you just need to provide the format of the CSV and pickle data files. I just want to learn this repository.

**Comment by lycantrope** [comment]
The format of csv file and pickle were both generated by DeepLabCut. Before you use or learn this repository, please check the document of DeepLabCut first. Finally, you can know the format of csv and pickle file. There is no point to learn this repository without the prior knowledge of the DeepLabCut.
